interface ServiceInterface {
  type: string;
  scope: string;
  notes: string;
  order: number;
  hoursEquipment: number;
  totalHours: number;
  unitValue: number;
  code: string;
  group: string;
  control: string;
}

export const dataSeed: ServiceInterface[] = [
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 1/2" hasta 2-1/2"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 1,
    hoursEquipment: 3.75,
    totalHours: 13.12,
    unitValue: 983343,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 3" hasta 6"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 2,
    hoursEquipment: 4.5,
    totalHours: 15.75,
    unitValue: 1180011,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 8" hasta 10"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 3,
    hoursEquipment: 6.43,
    totalHours: 22.5,
    unitValue: 1685737,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 12" hasta 14"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 4,
    hoursEquipment: 15,
    totalHours: 35,
    unitValue: 2301640,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 16" hasta 18"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 5,
    hoursEquipment: 18,
    totalHours: 42,
    unitValue: 3105376,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 20"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 6,
    hoursEquipment: 22.5,
    totalHours: 52.5,
    unitValue: 3881721,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 24"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 7,
    hoursEquipment: 30,
    totalHours: 70,
    unitValue: 5175628,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 30"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 8,
    hoursEquipment: 45,
    totalHours: 105,
    unitValue: 7763442,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 1/2" hasta 2-1/2"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 1,
    hoursEquipment: 4.09,
    totalHours: 14.31,
    unitValue: 1072742,
    code: '600',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 3" hasta 4"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 2,
    hoursEquipment: 5.62,
    totalHours: 19.68,
    unitValue: 1475020,
    code: '600',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 6" hasta 8"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 3,
    hoursEquipment: 8.18,
    totalHours: 28.63,
    unitValue: 2145484,
    code: '600',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 10"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 4,
    hoursEquipment: 10,
    totalHours: 35,
    unitValue: 2622258,
    code: '600',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 12"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 5,
    hoursEquipment: 22.5,
    totalHours: 52.5,
    unitValue: 3881721,
    code: '600',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 14"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 6,
    hoursEquipment: 25.71,
    totalHours: 60,
    unitValue: 4436252,
    code: '600',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 16"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 7,
    hoursEquipment: 30,
    totalHours: 70,
    unitValue: 5175628,
    code: '600',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 18"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 8,
    hoursEquipment: 36,
    totalHours: 84,
    unitValue: 6210753,
    code: '600',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 3"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 1,
    hoursEquipment: 6.43,
    totalHours: 22.5,
    unitValue: 1685737,
    code: '900',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 4"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 2,
    hoursEquipment: 7.5,
    totalHours: 26.25,
    unitValue: 1966694,
    code: '900',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 5"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 3,
    hoursEquipment: 16.36,
    totalHours: 38.18,
    unitValue: 2510880,
    code: '900',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 6"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 4,
    hoursEquipment: 18,
    totalHours: 42,
    unitValue: 2761968,
    code: '900',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 8"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 5,
    hoursEquipment: 20,
    totalHours: 46.67,
    unitValue: 3450418,
    code: '900',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 10"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 6,
    hoursEquipment: 25.71,
    totalHours: 60,
    unitValue: 4436252,
    code: '900',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 12"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 7,
    hoursEquipment: 36,
    totalHours: 84,
    unitValue: 6210753,
    code: '900',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 2" hasta 2-1/2"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 1,
    hoursEquipment: 6.43,
    totalHours: 22.5,
    unitValue: 1685737,
    code: '1500',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 3"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 2,
    hoursEquipment: 6.92,
    totalHours: 24.23,
    unitValue: 1815409,
    code: '1500',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 4"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 3,
    hoursEquipment: 7.5,
    totalHours: 26.25,
    unitValue: 1966694,
    code: '1500',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 5"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 4,
    hoursEquipment: 18,
    totalHours: 42,
    unitValue: 2761968,
    code: '1500',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 6"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 5,
    hoursEquipment: 22.5,
    totalHours: 52.5,
    unitValue: 3452460,
    code: '1500',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 8"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 6,
    hoursEquipment: 25.71,
    totalHours: 60,
    unitValue: 4436252,
    code: '1500',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 10"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 7,
    hoursEquipment: 30,
    totalHours: 70,
    unitValue: 5175628,
    code: '1500',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Válvulas Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 12"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 8,
    hoursEquipment: 45,
    totalHours: 105,
    unitValue: 7763442,
    code: '1500',
    group: 'Valves',
    control: '',
  },
  //########################### valvulas de seguridad
  {
    type: 'Valvulas de seguridad',
    scope:
      'a Valvula de Seguridad o Alivio del tipo bridadas o roscadas en diámetros desde 1/2" hasta 1", ANSI 150-300. Prueba de Set en que se recibe la valvula, desarme de válvula, limpieza de partes, revisión internos, pulido de disco y asiento, ajuste de Set de disparo, pruebas finales, pintura general.                                                                                                                                                                                                                      ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 1,
    hoursEquipment: 4.5,
    totalHours: 15.75,
    unitValue: 766781.17,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Valvulas de seguridad',
    scope:
      'a Valvula de Seguridad o Alivio del tipo bridadas o roscadas en diámetros desde 1-1/2" hasta 2", ANSI 150-300. Prueba de Set en que se recibe la valvula, desarme de válvula, limpieza de partes, revisión internos, pulido de disco y asiento, ajuste de Set de disparo, pruebas finales, pintura general.                                                                                                                                                                                                                          ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 2,
    hoursEquipment: 4.74,
    totalHours: 16.58,
    unitValue: 807138.07,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Valvulas de seguridad',
    scope:
      'a Valvula de Seguridad o Alivio del tipo bridadas o roscadas en diámetros desde 2-1/2" hasta 3", ANSI 150-300. Prueba de Set en que se recibe la valvula, desarme de válvula, limpieza de partes, revisión internos, pulido de disco y asiento, ajuste de Set de disparo, pruebas finales, pintura general.                                                                                                                                                                                                                           ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 3,
    hoursEquipment: 5.29,
    totalHours: 18.53,
    unitValue: 902095.49,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Valvulas de seguridad',
    scope:
      'a Valvula de Seguridad o Alivio del tipo bridadas o roscadas en diámetros de 4" ANSI 150-300. Prueba de Set en que se recibe la valvula, desarme de válvula, limpieza de partes, revisión internos, pulido de disco y asiento, ajuste de Set de disparo, pruebas finales, pintura general.                                                                                                                                                                                                                         ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 4,
    hoursEquipment: 5.62,
    totalHours: 26.25,
    unitValue: 1110068.55,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Valvulas de seguridad',
    scope:
      'a Valvula de Seguridad o Alivio del tipo bridadas o roscadas en diámetros de 6", ANSI 150-300. Prueba de Set en que se recibe la valvula, desarme de válvula, limpieza de partes, revisión internos, pulido de disco y asiento, ajuste de Set de disparo, pruebas finales, pintura general.                                                                                                                                                                                                                            ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 5,
    hoursEquipment: 6.0,
    totalHours: 28.0,
    unitValue: 1281343.83,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Valvulas de seguridad',
    scope:
      'a Valvula de Seguridad o Alivio del tipo bridadas o roscadas en diámetros de 8", ANSI 150-300. Prueba de Set en que se recibe la valvula, desarme de válvula, limpieza de partes, revisión internos, pulido de disco y asiento, ajuste de Set de disparo, pruebas finales, pintura general.                                                                                                                                                                                                                            ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 6,
    hoursEquipment: 6.43,
    totalHours: 30.0,
    unitValue: 1372868.39,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Valvulas de seguridad',
    scope:
      'a Valvula de Seguridad o Alivio del tipo bridadas o roscadas en diámetros de 10", ANSI 150-300.  Prueba de Set en que se recibe la valvula, desarme de válvula, limpieza de partes, revisión internos, pulido de disco y asiento, ajuste de Set de disparo, pruebas finales, pintura general.                                                                                                                                                                                                                            ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 7,
    hoursEquipment: 6.92,
    totalHours: 32.31,
    unitValue: 1548417.71,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  {
    type: 'Valvulas de seguridad',
    scope:
      'a Valvula de Seguridad o Alivio del tipo bridadas o roscadas en diámetros de 12" ANSI 150-300. Prueba de Set en que se recibe la valvula, desarme de válvula, limpieza de partes, revisión internos, pulido de disco y asiento, ajuste de Set de disparo, pruebas finales, pintura general.                                                                                                                                                                                           Nota: No se incluye repuestos ni maquinado de partes.                                   ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 8,
    hoursEquipment: 7.5,
    totalHours: 35.0,
    unitValue: 1677452.52,
    code: '150-300',
    group: 'Valves',
    control: '',
  },
  //################################# Válvulas de Control neumaticas
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula de Control con actuador neumático en diámetros desde 1/2" hasta 1-1/2", ANSI 150-300.',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 1,
    hoursEquipment: 5.62,
    totalHours: 19.69,
    unitValue: 958476.46,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Neumático',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula de Control con actuador neumático en diámetros desde 2" hasta 3", ANSI 150-300.',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 2,
    hoursEquipment: 6.43,
    totalHours: 22.5,
    unitValue: 1095401.67,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Neumático',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula de Control con actuador neumático en diámetros de 4", ANSI 150-300.                                  ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 3,
    hoursEquipment: 7.5,
    totalHours: 26.25,
    unitValue: 1277968.61,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Neumático',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula de Control con actuador neumático en diámetros de 6", ANSI 150-300.                         ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 4,
    hoursEquipment: 6.43,
    totalHours: 30.0,
    unitValue: 1268649.78,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Neumático',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula de Control con actuador neumático en diámetros de 8", ANSI 150-300.                                 ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 5,
    hoursEquipment: 7.5,
    totalHours: 35.0,
    unitValue: 1601679.79,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Neumático',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula de Control con actuador neumático en diámetros de 10", ANSI 150-300.                            ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 6,
    hoursEquipment: 9.0,
    totalHours: 42.0,
    unitValue: 1922015.75,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Neumático',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula de Control con actuador neumático en diámetros de 12", ANSI 150-300.                                  ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 7,
    hoursEquipment: 10.0,
    totalHours: 46.67,
    unitValue: 2236603.36,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Neumático',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula de Control con actuador neumático en diámetros de 14", ANSI 150-300.                                 ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 8,
    hoursEquipment: 11.25,
    totalHours: 52.5,
    unitValue: 2516178.78,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Neumático',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula de Control con actuador neumático en diámetros de 16", ANSI 150-300.                               ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 9,
    hoursEquipment: 15.0,
    totalHours: 52.5,
    unitValue: 2950659.45,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Neumático',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula de Control con actuador neumático en diámetros de 18", ANSI 150-300.',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 10,
    hoursEquipment: 18.0,
    totalHours: 63.0,
    unitValue: 3540791.34,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Neumático',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula de Control con actuador neumático en diámetros de 20", ANSI 150-300.',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 11,
    hoursEquipment: 22.5,
    totalHours: 78.75,
    unitValue: 4425989.17,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Neumático',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula de Control con actuador neumático en diámetros de 24", ANSI 150-300.                                  ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 12,
    hoursEquipment: 30.0,
    totalHours: 105.0,
    unitValue: 5901318.89,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Neumático',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula de Control con actuador neumático en diámetros de 30", ANSI 150-300.                               ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 13,
    hoursEquipment: 45.0,
    totalHours: 157.5,
    unitValue: 8851978.34,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Neumático',
  },
  // ################################### Válvulas de Control Actuador Eléctrico
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 1/2" hasta 1", ANSI 150-300. Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                  ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 1,
    hoursEquipment: 7.5,
    totalHours: 18.75,
    unitValue: 832201.87,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 1-1/2" hasta 2-1/2", ANSI 150-300.  Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                              ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 2,
    hoursEquipment: 8.18,
    totalHours: 20.45,
    unitValue: 965711.84,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 3" hasta 4", ANSI 150-300.  Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                             ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 3,
    hoursEquipment: 9.0,
    totalHours: 28.12,
    unitValue: 1157055.87,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 6" hasta 8", ANSI 150-300.  Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                               ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 4,
    hoursEquipment: 10.0,
    totalHours: 37.5,
    unitValue: 1413307.01,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 10" hasta 12", ANSI 150-300.  Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                   ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 5,
    hoursEquipment: 12.86,
    totalHours: 48.21,
    unitValue: 1942365.79,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 16" hasta 20", ANSI 150-300.  Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                 ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 6,
    hoursEquipment: 22.5,
    totalHours: 84.38,
    unitValue: 3160886.97,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetro 24", ANSI 150-300. Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                 ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 7,
    hoursEquipment: 45.0,
    totalHours: 168.75,
    unitValue: 6001971.04,
    code: '150-300',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'Mantenimiento general Valvula con actuador eléctrico en diámetros desde 1/2" hasta 1", ANSI 600-900. Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                   ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 8,
    hoursEquipment: 8.18,
    totalHours: 20.45,
    unitValue: 907856.59,
    code: '600-900',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 1-1/2" hasta 2-1/2", ANSI 600-900. Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                    ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 9,
    hoursEquipment: 9.0,
    totalHours: 22.5,
    unitValue: 1027424.51,
    code: '600-900',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 3" hasta 4", ANSI 600-900.  Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                  ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 10,
    hoursEquipment: 10.0,
    totalHours: 37.5,
    unitValue: 1355742.49,
    code: '600-900',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 6" hasta 8", ANSI 600-900.  Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                    ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 11,
    hoursEquipment: 12.86,
    totalHours: 48.21,
    unitValue: 1692842.74,
    code: '600-900',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'al Valvula con actuador eléctrico en diámetros desde 10" hasta 12", ANSI 600-900.  Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                  ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 12,
    hoursEquipment: 15.0,
    totalHours: 56.25,
    unitValue: 2184010.67,
    code: '600-900',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 16" hasta 20", ANSI 600-900. Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                       ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 13,
    hoursEquipment: 22.5,
    totalHours: 84.38,
    unitValue: 3160886.97,
    code: '600-900',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetro 24", ANSI 600-900. Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                     ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 14,
    hoursEquipment: 50.0,
    totalHours: 125.0,
    unitValue: 5445263.47,
    code: '600-900',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 1/2" hasta 1", ANSI 1500.  Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                     ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 15,
    hoursEquipment: 9.0,
    totalHours: 22.5,
    unitValue: 998642.24,
    code: '900-1500',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 1-1/2" hasta 2-1/2", ANSI 1500. Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                  ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 16,
    hoursEquipment: 10.0,
    totalHours: 25.0,
    unitValue: 1102851.1,
    code: '900-1500',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 3" hasta 4", ANSI 1500. Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                      ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 17,
    hoursEquipment: 11.25,
    totalHours: 42.19,
    unitValue: 1478039.37,
    code: '900-1500',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 6" hasta 8", ANSI 1500. Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                   ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 18,
    hoursEquipment: 15.0,
    totalHours: 56.25,
    unitValue: 1902494.55,
    code: '900-1500',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 10" hasta 12", ANSI 1500. Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales.                                                                                                                                                                                     ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 19,
    hoursEquipment: 18.0,
    totalHours: 90.0,
    unitValue: 2925709.95,
    code: '900-1500',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
  {
    type: 'Válvulas de Control',
    scope:
      'a Valvula con actuador eléctrico en diámetros desde 16" hasta 20", ANSI 1500. Limpieza y pintura cuerpo y actuador, revisión de actuador, revisión cuerpo e internos, pulido de obturador y asiento (lapeado si se requiere), cambio de partes blandas, revisión de solenoides, revisión de switches de posición, pruebas finales..                                                                                                                                                                                      ',
    notes: '1- No se incluye repuestos ni maquinado de partes.',
    order: 20,
    hoursEquipment: 30.0,
    totalHours: 150.0,
    unitValue: 4678971.46,
    code: '900-1500',
    group: 'Valves',
    control: 'Actuador Eléctrico',
  },
];
