interface ServiceInterface {
  type: string;
  scope: string;
  notes: string;
  order: number;
  hoursEquipment: number;
  totalHours: number;
  unitValue: number;
  code: string;
  group: string;
}

export const dataSeed: ServiceInterface[] = [
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 1/2" hasta 2-1/2"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 1,
    hoursEquipment: 3.75,
    totalHours: 13.12,
    unitValue: 983343,
    code: '150-300',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 3" hasta 6"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 2,
    hoursEquipment: 4.5,
    totalHours: 15.75,
    unitValue: 1180011,
    code: '150-300',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 8" hasta 10"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 3,
    hoursEquipment: 6.43,
    totalHours: 22.5,
    unitValue: 1685737,
    code: '150-300',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 12" hasta 14"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 4,
    hoursEquipment: 15,
    totalHours: 35,
    unitValue: 2301640,
    code: '150-300',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 16" hasta 18"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 5,
    hoursEquipment: 18,
    totalHours: 42,
    unitValue: 3105376,
    code: '150-300',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 20"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 6,
    hoursEquipment: 22.5,
    totalHours: 52.5,
    unitValue: 3881721,
    code: '150-300',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 24"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 7,
    hoursEquipment: 30,
    totalHours: 70,
    unitValue: 5175628,
    code: '150-300',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 30"  ANSI 150-300 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 8,
    hoursEquipment: 45,
    totalHours: 105,
    unitValue: 7763442,
    code: '150-300',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 1/2" hasta 2-1/2"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 1,
    hoursEquipment: 4.09,
    totalHours: 14.31,
    unitValue: 1072742,
    code: '600',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 3" hasta 4"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 2,
    hoursEquipment: 5.62,
    totalHours: 19.68,
    unitValue: 1475020,
    code: '600',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 6" hasta 8"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 3,
    hoursEquipment: 8.18,
    totalHours: 28.63,
    unitValue: 2145484,
    code: '600',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 10"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 4,
    hoursEquipment: 10,
    totalHours: 35,
    unitValue: 2622258,
    code: '600',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 12"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 5,
    hoursEquipment: 22.5,
    totalHours: 52.5,
    unitValue: 3881721,
    code: '600',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 14"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 6,
    hoursEquipment: 25.71,
    totalHours: 60,
    unitValue: 4436252,
    code: '600',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 16"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 7,
    hoursEquipment: 30,
    totalHours: 70,
    unitValue: 5175628,
    code: '600',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 18"  ANSI 600 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 8,
    hoursEquipment: 36,
    totalHours: 84,
    unitValue: 6210753,
    code: '600',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 3"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 1,
    hoursEquipment: 6.43,
    totalHours: 22.5,
    unitValue: 1685737,
    code: '900',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 4"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 2,
    hoursEquipment: 7.5,
    totalHours: 26.25,
    unitValue: 1966694,
    code: '900',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 5"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 3,
    hoursEquipment: 16.36,
    totalHours: 38.18,
    unitValue: 2510880,
    code: '900',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 6"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 4,
    hoursEquipment: 18,
    totalHours: 42,
    unitValue: 2761968,
    code: '900',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 8"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 5,
    hoursEquipment: 20,
    totalHours: 46.67,
    unitValue: 3450418,
    code: '900',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 10"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 6,
    hoursEquipment: 25.71,
    totalHours: 60,
    unitValue: 4436252,
    code: '900',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 12"  ANSI 900 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 7,
    hoursEquipment: 36,
    totalHours: 84,
    unitValue: 6210753,
    code: '900',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro desde 2" hasta 2-1/2"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 1,
    hoursEquipment: 6.43,
    totalHours: 22.5,
    unitValue: 1685737,
    code: '1500',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 3"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 2,
    hoursEquipment: 6.92,
    totalHours: 24.23,
    unitValue: 1815409,
    code: '1500',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 4"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 3,
    hoursEquipment: 7.5,
    totalHours: 26.25,
    unitValue: 1966694,
    code: '1500',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 5"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 4,
    hoursEquipment: 18,
    totalHours: 42,
    unitValue: 2761968,
    code: '1500',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 6"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 5,
    hoursEquipment: 22.5,
    totalHours: 52.5,
    unitValue: 3452460,
    code: '1500',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 8"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 6,
    hoursEquipment: 25.71,
    totalHours: 60,
    unitValue: 4436252,
    code: '1500',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 10"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 7,
    hoursEquipment: 30,
    totalHours: 70,
    unitValue: 5175628,
    code: '1500',
    group: 'Valves',
  },
  {
    type: 'Manuales',
    scope: `a valvula manuales de: compuerta, globo, bola, tapón y retención (cheque) en diámetro de 12"  ANSI 1500 de acuerdo a la norma API-598.
Desarme de válvula, limpieza de partes, de cuerpo e internos, pulido de compuerta, disco y/o asiento (lapeado si se requiere), cambio de empaques del bástago, cambio de junta cuerpo yugo/bonete, armado de válvula y pruebas de sello, certificación de pruebas, pintura total.`,
    notes: `1- No se incluye repuestos ni maquinado de partes.`,
    order: 8,
    hoursEquipment: 45,
    totalHours: 105,
    unitValue: 7763442,
    code: '1500',
    group: 'Valves',
  },
];
